SHEET_ID = 0 
TABLE_SIZE_ROW = 100

HEADER_ROW = 1
HEADER_COLUMNS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N"]
TABLE_SIZE_COLUMN = len(HEADER_COLUMNS) 
HEADER_NAMES = [
    "COMPANY",
    "JOB_POSITION",
    "DATE_APPLIED",
    "STATUS",
    "INDUSTRY",
    "LOCATION",
    "SCORE",
    "YEARS_OF_EXPERIENCE",
    "JOB_DESCRIPTION",
    "PAY_RANGE",
    "INTERVIEW_PROCESS",
    "EXAMPLE_INTERVIEW_EXPERIENCE",
    "CAREER_GROWTH",
    "EXAMPLE_TECHNICAL_QUESTIONS"
]

