SHEET_ID = 0 
TABLE_SIZE_ROW = 100
TABLE_SIZE_COLUMN = 9
HEADER_ROW = 1
HEADER_COLUMNS = ["A","B","C","D","E","F","G","H","I"]
HEADER_NAMES = [
    "COMPANY",
    "POSITION",
    "STATUS",
    "JOB_DESCRIPTION",
    "PAY_RANGE",
    "INTERVIEW_PROCESS",
    "EXAMPLE_INTERVIEW_EXPERIENCE",
    "CAREER_GROWTH",
    "EXAMPLE_TECHNICAL_QUESTIONS"
]

